version: "3"

services:
  text_to_gestures_model_test:
    build: .
    ports:
      - "2000:22"
    user: $DOCKER_USER:$DOCKER_GROUP
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             capabilities: [gpu]
    volumes:
      - '../dataset_dir/:/home/Hosting/workspace/dataset_dir:rw'
      - './:/home/Hosting/workspace:rw'
      - '~/.ssh:/home/Hosting/.ssh:ro'
