version: "3"

services:
  text_to_gestures_model_test:
    build: .
    ports:
      - 8080:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 0
              capabilities: [gpu]
<<<<<<< Updated upstream
=======
    volumes:
      - '../dataset_dir:/workspace/dataset_dir'
>>>>>>> Stashed changes
